FROM centos:6
MAINTAINER David M. Lee, II <dlee@respoke.io>

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm && \
    yum groupinstall -y "Development Tools" && \
    yum install -y pjproject-devel
