# -*- Dockerfile -*-

FROM asterisk:ubuntu-trusty
MAINTAINER David M. Lee, II <dlee@respoke.io>

RUN apt-get update -qq && \
    apt-get install -y \
            build-essential \
            ccache \
            git \
            && \
    apt-get purge -y --auto-remove && rm -rf /var/lib/apt/lists/*

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]

COPY build-chan_respoke.sh /build-chan_respoke
CMD ["/build-chan_respoke"]
