FROM pjsip:ubuntu-trusty
MAINTAINER David M. Lee, II <dlee@respoke.io>

ENV DEBIAN_FRONTEND=noninteractive

RUN useradd --system asterisk

RUN apt-get update -qq && \
    apt-get install -yqq curl build-essential libgsm1-dev libssl-dev \
            portaudio19-dev libspeex-dev libspeexdsp-dev libsrtp0-dev \
            binutils-dev doxygen freetds-dev libbluetooth-dev \
            libcorosync-dev libcurl4-openssl-dev libedit-dev libgtk2.0-dev \
            libical-dev libiksemel-dev libjansson-dev liblua5.1-0-dev \
            libmysqlclient-dev libneon27-dev libnewt-dev libogg-dev \
            libpopt-dev libpq-dev libradiusclient-ng-dev libsnmp-dev \
            libspandsp-dev libsqlite0-dev libsqlite3-dev libusb-dev \
            libvorbis-dev libvpb-dev libxml2-dev libxslt1-dev lua5.1 \
            unixodbc-dev uuid uuid-dev && \
    apt-get purge -y --auto-remove && rm -rf /var/lib/apt/lists/*

ENV ASTERISK_VERSION=13.5.0
COPY build-asterisk.sh /build-asterisk
RUN /build-asterisk
RUN mkdir /usr/src/asterisk && \
    cd /usr/src/asterisk && \
    curl -sL http://downloads.asterisk.org/pub/telephony/asterisk/releases/asterisk-${ASTERISK_VERSION}.tar.gz | \
    	 tar --strip-components 1 --xz && \
    ./configure --prefix=/usr/local && \
    for i in CORE-SOUNDS-EN MOH-OPSOUND EXTRA-SOUNDS-EN; do \
        for j in WAV ULAW ALAW G722 GSM; do \
            menuselect/menuselect --enable $i-$j menuselect.makeopts \
        done \
    done && \
    make all install samples && \
    

WORKDIR /usr/src/asterisk

COPY build-asterisk.sh /usr/local/bin/build-asterisk

CMD ["/usr/local/bin/build-asterisk"]
