# -*- Dockerfile -*-

FROM centos:6
MAINTAINER David M. Lee, II <dlee@respoke.io>

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm && \
    yum groupinstall -y "Development Tools"

RUN yum install -y gsm-devel openssl-devel portaudio-devel speex-devel \
        libsrtp-devel

RUN mkdir /usr/src/pjproject
WORKDIR /usr/src/pjproject

COPY config_site.h /tmp/
COPY build-pjsip.sh /build-pjsip
