# -*- Dockerfile -*-

FROM centos:6
MAINTAINER David M. Lee, II <dlee@respoke.io>

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm && \
    yum groupinstall -y "Development Tools" && \
    yum install -y \
        gsm-devel \
        openssl-devel \
        portaudio-devel \
        speex-devel \
        libsrtp-devel && \
    yum clean all

COPY config_site.h /tmp/
COPY build-pjsip.sh /build-pjsip
