# -*- Dockerfile -*-

FROM ubuntu:trusty
MAINTAINER David M. Lee, II <dlee@respoke.io>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && \
    apt-get install -y \
            build-essential \
            ccache \
            curl \
            libgsm1-dev \
            libspeex-dev \
            libspeexdsp-dev \
            libsrtp0-dev \
            libssl-dev \
            portaudio19-dev \
            && \
    apt-get purge -y --auto-remove && rm -rf /var/lib/apt/lists/*

RUN mkdir /usr/src/pjsip
WORKDIR /usr/src/pjsip

COPY config_site.h /tmp/
COPY build-pjsip.sh /build-pjsip
